version: "3.9"
services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      - DEBUG
      - SECRET_KEY
      - ALLOWED_HOSTS
      - EMAIL_URL
      - SERVER_EMAIL
      - DEFAULT_FROM_EMAIL
      - EMAIL_SSL_CERTFILE
      - EMAIL_SSL_KEYFILE
      - BOTO
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
      - AWS_S3_REGION_NAME
      - AWS_S3_ENDPOINT_URL
      - DATABASE_URL=psql://postgres:test_password@db:5432/cnotes

    command: >
      sh -c "cd app &&
             gunicorn -b 0.0.0.0:8080 cnotes.wsgi"
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=cnotes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test_password
