# Generated by Django 3.1.6 on 2021-02-12 04:19

import core.models
from django.db import migrations, models
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único seguindo o padrão UUID4.', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título do caderno.', max_length=255, verbose_name='título')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Data de criação do caderno.', verbose_name='data de criação')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, help_text='Pequena descrição pública do usuário.', max_length=360, null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único seguindo o padrão UUID4.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se a conta do usuário está ativa.', verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indica se o usuário é um administrador do sistema.', verbose_name='staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, help_text='Imagem de perfil do usuário.', keep_meta=True, null=True, quality=75, size=[512, 512], upload_to=core.models.profile_picture_path, verbose_name='foto de perfil'),
        ),
    ]
