# Generated by Django 3.1.6 on 2021-02-14 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='owner',
            field=models.ForeignKey(help_text='Atual dono do caderno.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='dono'),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único seguindo o padrão UUID4.', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título da pasta.', max_length=255, verbose_name='título')),
                ('notebook', models.ForeignKey(help_text='Caderno onde a pasta se localiza.', on_delete=django.db.models.deletion.CASCADE, to='core.notebook', verbose_name='caderno')),
                ('parent_folder', models.ForeignKey(blank=True, help_text='Pasta em que esta pasta se localiza, em caso de nulo, pasta raiz.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.folder', verbose_name='pasta pai')),
            ],
            options={
                'verbose_name': 'pasta',
                'verbose_name_plural': 'pastas',
            },
        ),
    ]
