# Generated by Django 3.1.6 on 2021-03-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210317_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='is_viewed',
            new_name='seen',
        ),
    ]
