# Generated by Django 3.1.6 on 2021-02-14 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210214_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='notebook',
            field=models.ForeignKey(help_text='Caderno onde a pasta se localiza.', on_delete=django.db.models.deletion.CASCADE, related_name='folders', related_query_name='folder', to='core.notebook', verbose_name='caderno'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, help_text='Pasta em que esta pasta se localiza, em caso de nulo, pasta raiz.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_folders', related_query_name='sub_folder', to='core.folder', verbose_name='pasta pai'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='owner',
            field=models.ForeignKey(help_text='Atual dono do caderno.', on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', related_query_name='notebook', to=settings.AUTH_USER_MODEL, verbose_name='dono'),
        ),
        migrations.CreateModel(
            name='NoteGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único seguindo o padrão UUID4.', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título da pasta.', max_length=255, verbose_name='título')),
                ('parent_folder', models.ForeignKey(blank=True, help_text='Pasta em que esta pasta se localiza, em caso de nulo, pasta raiz', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_groups', related_query_name='note_group', to='core.folder', verbose_name='pasta pai')),
            ],
            options={
                'verbose_name': 'conjunto de anotação',
                'verbose_name_plural': 'conjunto de anotações',
            },
        ),
    ]
