# Generated by Django 3.1.6 on 2021-02-12 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210212_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='title',
            field=models.CharField(help_text='Título do caderno.', max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='título'),
        ),
    ]
