# Generated by Django 3.1.6 on 2021-02-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210214_0142'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(parent_folder=None), fields=('notebook',), name='unique_parent_folder'),
        ),
    ]
