# Generated by Django 3.1.7 on 2021-03-20 21:51

import core.models.attachment
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210318_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único seguindo o padrão UUID4.', primary_key=True, serialize=False)),
                ('uploaded_file', models.FileField(help_text='O arquivo anexado.', upload_to=core.models.attachment.attachment_file_path, verbose_name='arquivo anexado')),
                ('uploaded_at', models.DateTimeField(auto_now=True, help_text='Momento da última modificação no anexo.', verbose_name='enviada em')),
                ('note', models.ForeignKey(help_text='Anotação onde o anexo se localiza.', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', related_query_name='attachment', to='core.note', verbose_name='anotação')),
            ],
        ),
    ]
