# Generated by Django 3.1.6 on 2021-02-16 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210214_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único seguindo o padrão UUID4.', primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('mod', 'Moderator'), ('admin', 'Administrator')], default='member', help_text='Papel desempenhado pelo membro dentro do caderno', max_length=6)),
                ('member_since', models.DateTimeField(auto_now_add=True, help_text='Data de entrada do membro no caderno', verbose_name='Data de entrada')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o membro está ativo', verbose_name='ativo')),
                ('is_banned', models.BooleanField(default=False, help_text='Indica se o membro está banido', verbose_name='banido')),
                ('notebook', models.ForeignKey(help_text='Caderno no qual o usuário é membro', on_delete=django.db.models.deletion.CASCADE, to='core.notebook', verbose_name='caderno')),
                ('user', models.ForeignKey(help_text='Usuário membro de um caderno', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'membro',
                'verbose_name_plural': 'membros',
            },
        ),
    ]
