# Generated by Django 3.1.7 on 2021-03-30 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Indica quando a atividade ocorreu', verbose_name='data de criação'),
            preserve_default=False,
        ),
    ]
