# Generated by Django 3.1.6 on 2021-02-17 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se o usuário ainda é membro do caderno', verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_since',
            field=models.DateTimeField(auto_now_add=True, help_text='Data de entrada do membro no caderno', verbose_name='data de entrada'),
        ),
        migrations.AlterField(
            model_name='member',
            name='notebook',
            field=models.ForeignKey(help_text='Caderno no qual o usuário é membro', on_delete=django.db.models.deletion.CASCADE, related_name='members', related_query_name='member', to='core.notebook', verbose_name='caderno'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('member', 'membro'), ('mod', 'moderador'), ('admin', 'administrador')], default='member', help_text='Papel desempenhado pelo membro dentro do caderno', max_length=6),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(help_text='Usuário membro de um caderno', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', related_query_name='membership', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único seguindo o padrão UUID4.', primary_key=True, serialize=False)),
                ('invite_date', models.DateTimeField(auto_now_add=True, help_text='Data do envio do convite para um usuário', verbose_name='data do convite')),
                ('receiver', models.ForeignKey(help_text='Usuário destinatário do convite', on_delete=django.db.models.deletion.CASCADE, related_name='invites', related_query_name='invite', to=settings.AUTH_USER_MODEL, verbose_name='destinatário')),
                ('sender', models.ForeignKey(help_text='Usuário remetende do convite', on_delete=django.db.models.deletion.CASCADE, related_name='invites', related_query_name='invite', to='core.member', verbose_name='remetente')),
            ],
            options={
                'verbose_name': 'convite',
                'verbose_name_plural': 'convites',
            },
        ),
    ]
