# Generated by Django 3.1.6 on 2021-02-17 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210217_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='sender',
            field=models.ForeignKey(help_text='Usuário remetende do convite', on_delete=django.db.models.deletion.CASCADE, related_name='invites_sent', related_query_name='invite_sent', to='core.member', verbose_name='remetente'),
        ),
    ]
