# Generated by Django 3.1.6 on 2021-02-17 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210217_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único seguindo o padrão UUID4.', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título da atividade', max_length=255, verbose_name='título')),
                ('description', models.CharField(help_text='Descrição da atividade', max_length=255, verbose_name='descrição')),
                ('is_viewed', models.BooleanField(default=False, help_text='Indica se a atividade foi vista', verbose_name='visto')),
                ('user', models.ForeignKey(help_text='Usuário que verá suas atividades', on_delete=django.db.models.deletion.CASCADE, related_name='activities', related_query_name='activity', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'atividade',
                'verbose_name_plural': 'atividades',
            },
        ),
    ]
