# Generated by Django 3.1.6 on 2021-03-02 14:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='sender',
            field=models.ForeignKey(help_text='Usuário remetente do convite', on_delete=django.db.models.deletion.CASCADE, related_name='invites_sent', related_query_name='invite_sent', to='core.member', verbose_name='remetente'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único seguindo o padrão UUID4.', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título da anotação.', max_length=255, verbose_name='título')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Data de criação da anotação.', verbose_name='data de criação')),
                ('content', models.TextField(blank=True, help_text='Conteúdo da anotação.', verbose_name='conteúdo')),
                ('author', models.ForeignKey(help_text='Autor da anotação.', on_delete=django.db.models.deletion.CASCADE, related_name='notes', related_query_name='note', to='core.member', verbose_name='autor')),
                ('note_group', models.ForeignKey(help_text='Conjunto de anotações onde a anotação está contida.', on_delete=django.db.models.deletion.CASCADE, related_name='notes', related_query_name='note', to='core.notegroup', verbose_name='conjunto de anotações')),
            ],
            options={
                'verbose_name': 'anotação',
                'verbose_name_plural': 'anotações',
            },
        ),
    ]
