# Generated by Django 3.1.6 on 2021-03-06 18:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210302_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único seguindo o padrão UUID4.', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='valor da avaliação dada', verbose_name='avaliação')),
                ('rated_date', models.DateTimeField(auto_now=True, help_text='Data da avaliação.', verbose_name='data da avaliação')),
                ('note', models.ForeignKey(editable=False, help_text='anotação avaliada', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', related_query_name='rating', to='core.note', verbose_name='anotação')),
                ('rater', models.ForeignKey(editable=False, help_text='Autor da avaliação.', on_delete=django.db.models.deletion.CASCADE, related_name='rates', related_query_name='rate', to='core.member', verbose_name='avaliador')),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'avaliações',
                'unique_together': {('note', 'rater')},
            },
        ),
    ]
