# Generated by Django 3.1.6 on 2021-03-06 21:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='note',
            field=models.ForeignKey(editable=False, help_text='Anotação avaliada.', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', related_query_name='rating', to='core.note', verbose_name='anotação'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(help_text='Valor da avaliação dada.', verbose_name='avaliação'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único seguindo o padrão UUID4.', primary_key=True, serialize=False)),
                ('message', models.CharField(help_text='Conteúdo do comentário.', max_length=1023, verbose_name='mensagem')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Data de criação do comentário.', verbose_name='data de criação')),
                ('solved', models.BooleanField(default=False, help_text='Indicativo de que o comentário já foi resolvido', verbose_name='resolvido')),
                ('commenter', models.ForeignKey(editable=False, help_text='Autor do comentário.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='core.member', verbose_name='comentarista')),
                ('note', models.ForeignKey(editable=False, help_text='Anotação comentada.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='core.note', verbose_name='anotação')),
            ],
            options={
                'verbose_name': 'comentário',
                'verbose_name_plural': 'comentários',
            },
        ),
    ]
