# Generated by Django 3.1.6 on 2021-03-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210306_1800'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('user', 'notebook')},
        ),
    ]
