# Generated by Django 3.1.6 on 2021-03-10 00:46

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210309_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notegroup',
            name='parent_folder',
            field=models.ForeignKey(blank=True, help_text='Pasta em que este conjunto se localiza', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_groups', related_query_name='note_group', to='core.folder', verbose_name='pasta pai'),
        ),
        migrations.AlterField(
            model_name='notegroup',
            name='title',
            field=models.CharField(help_text='Título do conjunto.', max_length=255, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='', help_text='Pequena descrição pública do usuário.', max_length=360, verbose_name='bio'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, id=django.db.models.expressions.F('parent_folder')), name='no_self_reference'),
        ),
    ]
